# Generated by Django 3.0.5 on 2021-06-13 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'account',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('city', models.CharField(blank=True, db_column='City', max_length=255, null=True)),
                ('district', models.CharField(blank=True, db_column='District', max_length=255, null=True)),
                ('town', models.CharField(blank=True, db_column='Town', max_length=255, null=True)),
                ('street', models.CharField(blank=True, db_column='Street', max_length=255, null=True)),
                ('description', models.CharField(blank=True, db_column='Description', max_length=255, null=True)),
            ],
            options={
                'db_table': 'address',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=255, null=True)),
                ('description', models.CharField(blank=True, db_column='Description', max_length=255, null=True)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Contactinfo',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('phonenumber', models.CharField(blank=True, db_column='PhoneNumber', max_length=255, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=255, null=True)),
            ],
            options={
                'db_table': 'contactinfo',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Fullname',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('firstname', models.CharField(blank=True, db_column='FirstName', max_length=255, null=True)),
                ('middlename', models.CharField(blank=True, db_column='MiddleName', max_length=255, null=True)),
                ('lastname', models.CharField(blank=True, db_column='LastName', max_length=255, null=True)),
            ],
            options={
                'db_table': 'fullname',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=255, null=True)),
                ('description', models.CharField(blank=True, db_column='Description', max_length=255, null=True)),
            ],
            options={
                'db_table': 'genre',
            },
        ),
        migrations.CreateModel(
            name='Historyline',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'historyline',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('price', models.BigIntegerField(blank=True, db_column='Price', null=True)),
                ('description', models.CharField(blank=True, db_column='Description', max_length=255, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='products/images/')),
            ],
            options={
                'db_table': 'item',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('time', models.DateField(blank=True, db_column='Time', null=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=255, null=True)),
                ('addressid', models.ForeignKey(blank=True, db_column='AddressID', null=True, on_delete=django.db.models.deletion.CASCADE, to='ecomapp.Address')),
                ('customerid', models.ForeignKey(db_column='CustomerID', on_delete=django.db.models.deletion.CASCADE, to='ecomapp.Customer')),
                ('historylineid', models.ForeignKey(db_column='HistoryLineID', on_delete=django.db.models.deletion.CASCADE, to='ecomapp.Historyline')),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('amount', models.IntegerField(blank=True, db_column='Amount', null=True)),
                ('method', models.CharField(blank=True, db_column='Method', max_length=255, null=True)),
            ],
            options={
                'db_table': 'payment',
            },
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=255, null=True)),
                ('phonenumber', models.CharField(blank=True, db_column='PhoneNumber', max_length=255, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=255, null=True)),
            ],
            options={
                'db_table': 'producer',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('manufacturingdate', models.DateField(blank=True, db_column='ManufacturingDate', null=True)),
                ('expirydate', models.DateField(blank=True, db_column='ExpiryDate', null=True)),
                ('type', models.CharField(blank=True, db_column='Type', max_length=255, null=True)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=255, null=True)),
                ('producerid', models.ForeignKey(db_column='ProducerID', on_delete=django.db.models.deletion.CASCADE, to='ecomapp.Producer')),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Reviewreply',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('message', models.CharField(blank=True, db_column='Message', max_length=255, null=True)),
                ('time', models.DateField(blank=True, db_column='Time', null=True)),
            ],
            options={
                'db_table': 'reviewreply',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=255, null=True)),
                ('phonenumber', models.CharField(blank=True, db_column='PhoneNumber', max_length=255, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=255, null=True)),
            ],
            options={
                'db_table': 'supplier',
            },
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('content', models.CharField(blank=True, db_column='Content', max_length=255, null=True)),
            ],
            options={
                'db_table': 'tax',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('dateofbirth', models.DateField(blank=True, db_column='DateOfBirth', null=True)),
                ('gender', models.CharField(blank=True, db_column='Gender', max_length=255, null=True)),
                ('accountid', models.OneToOneField(blank=True, db_column='AccountID', null=True, on_delete=django.db.models.deletion.CASCADE, to='ecomapp.Account')),
                ('addressid', models.OneToOneField(blank=True, db_column='AddressID', null=True, on_delete=django.db.models.deletion.CASCADE, to='ecomapp.Address')),
                ('contactinfoid', models.OneToOneField(blank=True, db_column='ContactInfoID', null=True, on_delete=django.db.models.deletion.CASCADE, to='ecomapp.Contactinfo')),
                ('fullnameid', models.OneToOneField(blank=True, db_column='FullNameID', null=True, on_delete=django.db.models.deletion.CASCADE, to='ecomapp.Fullname')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=255, null=True)),
                ('discountpercent', models.FloatField(blank=True, db_column='DiscountPercent', null=True)),
                ('discountamount', models.IntegerField(blank=True, db_column='DiscountAmount', null=True)),
                ('description', models.CharField(blank=True, db_column='Description', max_length=255, null=True)),
            ],
            options={
                'db_table': 'voucher',
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('customerid', models.ForeignKey(db_column='CustomerID', on_delete=django.db.models.deletion.CASCADE, to='ecomapp.Customer')),
            ],
            options={
                'db_table': 'wishlist',
            },
        ),
        migrations.CreateModel(
            name='Banking',
            fields=[
                ('banktransactioncode', models.CharField(blank=True, db_column='BankTransactionCode', max_length=255, null=True)),
                ('paymentid', models.OneToOneField(db_column='PaymentID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ecomapp.Payment')),
            ],
            options={
                'db_table': 'banking',
            },
        ),
        migrations.CreateModel(
            name='Cash',
            fields=[
                ('recieve', models.IntegerField(blank=True, db_column='Recieve', null=True)),
                ('paymentid', models.OneToOneField(db_column='PaymentID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ecomapp.Payment')),
            ],
            options={
                'db_table': 'cash',
            },
        ),
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('clothtype', models.CharField(blank=True, db_column='ClothType', max_length=255, null=True)),
                ('color', models.CharField(blank=True, db_column='Color', max_length=255, null=True)),
                ('gender', models.CharField(blank=True, db_column='Gender', max_length=255, null=True)),
                ('ages', models.IntegerField(blank=True, db_column='Ages', null=True)),
                ('brand', models.CharField(blank=True, db_column='Brand', max_length=255, null=True)),
                ('material', models.CharField(blank=True, db_column='Material', max_length=255, null=True)),
                ('productid', models.OneToOneField(db_column='ProductID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ecomapp.Product')),
            ],
            options={
                'db_table': 'clothes',
            },
        ),
        migrations.CreateModel(
            name='Electronic',
            fields=[
                ('devicetype', models.CharField(blank=True, db_column='DeviceType', max_length=255, null=True)),
                ('color', models.CharField(blank=True, db_column='Color', max_length=255, null=True)),
                ('brand', models.CharField(blank=True, db_column='Brand', max_length=255, null=True)),
                ('material', models.CharField(blank=True, db_column='Material', max_length=255, null=True)),
                ('power', models.CharField(blank=True, db_column='Power', max_length=255, null=True)),
                ('voltage', models.CharField(blank=True, db_column='Voltage', max_length=255, null=True)),
                ('electriccurrent', models.CharField(blank=True, db_column='ElectricCurrent', max_length=255, null=True)),
                ('frequency', models.CharField(blank=True, db_column='Frequency', max_length=255, null=True)),
                ('productid', models.OneToOneField(db_column='ProductID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ecomapp.Product')),
            ],
            options={
                'db_table': 'electronic',
            },
        ),
        migrations.CreateModel(
            name='Qrcode',
            fields=[
                ('code', models.CharField(blank=True, db_column='Code', max_length=255, null=True)),
                ('paymentid', models.OneToOneField(db_column='PaymentID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ecomapp.Payment')),
            ],
            options={
                'db_table': 'qrcode',
            },
        ),
        migrations.CreateModel(
            name='Staffs',
            fields=[
                ('position', models.CharField(blank=True, db_column='Position', max_length=255, null=True)),
                ('salary', models.BigIntegerField(blank=True, db_column='Salary', null=True)),
                ('startdate', models.DateField(blank=True, db_column='StartDate', null=True)),
                ('workingtime', models.IntegerField(blank=True, db_column='WorkingTime', null=True)),
                ('userid', models.OneToOneField(db_column='UsersID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ecomapp.Users')),
            ],
            options={
                'db_table': 'staffs',
            },
        ),
        migrations.CreateModel(
            name='Wishlistline',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('itemid', models.ForeignKey(blank=True, db_column='ItemID', null=True, on_delete=django.db.models.deletion.CASCADE, to='ecomapp.Item')),
                ('wishlistid', models.ForeignKey(blank=True, db_column='WishListID', null=True, on_delete=django.db.models.deletion.CASCADE, to='ecomapp.Wishlist')),
            ],
            options={
                'db_table': 'wishlistline',
            },
        ),
        migrations.CreateModel(
            name='Shoppingcart',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('customerid', models.ForeignKey(db_column='CustomerID', on_delete=django.db.models.deletion.CASCADE, to='ecomapp.Customer')),
            ],
            options={
                'db_table': 'shoppingcart',
            },
        ),
        migrations.CreateModel(
            name='Shippinginfo',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('region', models.CharField(blank=True, db_column='Region', max_length=255, null=True)),
                ('cost', models.CharField(blank=True, db_column='Cost', max_length=255, null=True)),
                ('delaydate', models.CharField(blank=True, db_column='DelayDate', max_length=255, null=True)),
                ('note', models.CharField(blank=True, db_column='Note', max_length=255, null=True)),
                ('orderid', models.ForeignKey(db_column='OrderID', on_delete=django.db.models.deletion.CASCADE, to='ecomapp.Order')),
            ],
            options={
                'db_table': 'shippinginfo',
            },
        ),
        migrations.CreateModel(
            name='Shippingaddress',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('note', models.CharField(blank=True, db_column='Note', max_length=255, null=True)),
                ('addressid', models.ForeignKey(blank=True, db_column='AddressID', null=True, on_delete=django.db.models.deletion.CASCADE, to='ecomapp.Address')),
            ],
            options={
                'db_table': 'shippingaddress',
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=255, null=True)),
                ('percent', models.FloatField(db_column='Percent')),
                ('expirydate', models.DateField(blank=True, db_column='ExpiryDate', null=True)),
                ('itemid', models.ForeignKey(db_column='ItemID', on_delete=django.db.models.deletion.CASCADE, to='ecomapp.Item')),
            ],
            options={
                'db_table': 'promotion',
            },
        ),
        migrations.CreateModel(
            name='Prodimage',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='products/images/')),
                ('productid', models.ForeignKey(db_column='ProductID', on_delete=django.db.models.deletion.CASCADE, to='ecomapp.Product')),
            ],
            options={
                'db_table': 'prodimage',
            },
        ),
        migrations.CreateModel(
            name='Orderitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(blank=True, null=True)),
                ('itemid', models.ForeignKey(db_column='ItemID', on_delete=django.db.models.deletion.CASCADE, to='ecomapp.Item')),
                ('orderid', models.ForeignKey(db_column='OrderID', on_delete=django.db.models.deletion.CASCADE, to='ecomapp.Order')),
            ],
            options={
                'db_table': 'orderitem',
            },
        ),
        migrations.CreateModel(
            name='Orderhistory',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('note', models.CharField(blank=True, db_column='Note', max_length=255, null=True)),
                ('customerid', models.ForeignKey(db_column='CustomerID', on_delete=django.db.models.deletion.CASCADE, to='ecomapp.Customer')),
            ],
            options={
                'db_table': 'orderhistory',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='paymentid',
            field=models.ForeignKey(db_column='PaymentID', on_delete=django.db.models.deletion.CASCADE, to='ecomapp.Payment'),
        ),
        migrations.AddField(
            model_name='order',
            name='taxid',
            field=models.ForeignKey(db_column='TaxID', on_delete=django.db.models.deletion.CASCADE, to='ecomapp.Tax'),
        ),
        migrations.AddField(
            model_name='order',
            name='voucherid',
            field=models.ForeignKey(db_column='VoucherID', on_delete=django.db.models.deletion.CASCADE, to='ecomapp.Voucher'),
        ),
        migrations.CreateModel(
            name='Messagesession',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('customerid', models.ForeignKey(db_column='CustomerID', on_delete=django.db.models.deletion.CASCADE, to='ecomapp.Customer')),
            ],
            options={
                'db_table': 'messagesession',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('message', models.CharField(blank=True, db_column='Message', max_length=255, null=True)),
                ('time', models.DateField(blank=True, db_column='Time', null=True)),
                ('senderid', models.IntegerField(blank=True, db_column='SenderID', null=True)),
                ('messagesessionid', models.ForeignKey(blank=True, db_column='MessageSessionID', null=True, on_delete=django.db.models.deletion.CASCADE, to='ecomapp.Messagesession')),
            ],
            options={
                'db_table': 'message',
            },
        ),
        migrations.CreateModel(
            name='Membershiptype',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=255, null=True)),
                ('description', models.CharField(blank=True, db_column='Description', max_length=255, null=True)),
                ('condition', models.CharField(blank=True, db_column='Condition', max_length=255, null=True)),
                ('customerid', models.ForeignKey(db_column='CustomerID', on_delete=django.db.models.deletion.CASCADE, to='ecomapp.Customer')),
            ],
            options={
                'db_table': 'membershiptype',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='productid',
            field=models.ForeignKey(db_column='ProductID', on_delete=django.db.models.deletion.CASCADE, to='ecomapp.Product'),
        ),
        migrations.AddField(
            model_name='historyline',
            name='orderhistoryid',
            field=models.ForeignKey(db_column='OrderHistoryID', on_delete=django.db.models.deletion.CASCADE, to='ecomapp.Orderhistory'),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('rate', models.CharField(blank=True, db_column='Rate', max_length=255, null=True)),
                ('content', models.CharField(blank=True, db_column='Content', max_length=255, null=True)),
                ('customerid', models.ForeignKey(db_column='CustomerID', on_delete=django.db.models.deletion.CASCADE, to='ecomapp.Customer')),
                ('itemid', models.ForeignKey(db_column='ItemID', on_delete=django.db.models.deletion.CASCADE, to='ecomapp.Item')),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
        migrations.CreateModel(
            name='Customerreview',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('content', models.CharField(blank=True, db_column='Content', max_length=255, null=True)),
                ('reviewtime', models.TimeField(blank=True, db_column='ReviewTime', null=True)),
                ('customerid', models.ForeignKey(db_column='CustomerID', on_delete=django.db.models.deletion.CASCADE, to='ecomapp.Customer')),
                ('reviewreplyid', models.ForeignKey(blank=True, db_column='ReviewReplyID', null=True, on_delete=django.db.models.deletion.CASCADE, to='ecomapp.Reviewreply')),
            ],
            options={
                'db_table': 'customerreview',
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='userid',
            field=models.OneToOneField(blank=True, db_column='CustomerID', null=True, on_delete=django.db.models.deletion.CASCADE, to='ecomapp.Users'),
        ),
        migrations.CreateModel(
            name='Cartline',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('num', models.IntegerField(blank=True, db_column='Num', null=True)),
                ('itemid', models.ForeignKey(db_column='ItemID', on_delete=django.db.models.deletion.CASCADE, to='ecomapp.Item')),
                ('shoppingcartid', models.ForeignKey(db_column='ShoppingCartID', on_delete=django.db.models.deletion.CASCADE, to='ecomapp.Shoppingcart')),
            ],
            options={
                'db_table': 'cartline',
            },
        ),
        migrations.CreateModel(
            name='Businessstaff',
            fields=[
                ('numproductprocessed', models.IntegerField(blank=True, db_column='NumProductProcessed', null=True)),
                ('staffid', models.OneToOneField(db_column='StaffID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ecomapp.Staffs')),
            ],
            options={
                'db_table': 'businessstaff',
            },
        ),
        migrations.CreateModel(
            name='Salesstaff',
            fields=[
                ('numorderprocessed', models.IntegerField(blank=True, db_column='NumOrderProcessed', null=True)),
                ('staffid', models.OneToOneField(db_column='StaffID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ecomapp.Staffs')),
            ],
            options={
                'db_table': 'salesstaff',
            },
        ),
        migrations.CreateModel(
            name='Warehousestaff',
            fields=[
                ('numbills', models.IntegerField(blank=True, db_column='NumBills', null=True)),
                ('staffid', models.OneToOneField(db_column='StaffID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ecomapp.Staffs')),
            ],
            options={
                'db_table': 'warehousestaff',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('page', models.IntegerField(blank=True, db_column='Page', null=True)),
                ('quantity', models.IntegerField(blank=True, db_column='Quantity', null=True)),
                ('productid', models.OneToOneField(db_column='ProductID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ecomapp.Product')),
                ('genreid', models.ForeignKey(db_column='GenreID', on_delete=django.db.models.deletion.CASCADE, to='ecomapp.Genre')),
            ],
            options={
                'db_table': 'book',
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('dateofbirth', models.DateField(blank=True, db_column='DateOfBirth', null=True)),
                ('fullnameid', models.OneToOneField(blank=True, db_column='FullNameID', null=True, on_delete=django.db.models.deletion.CASCADE, to='ecomapp.Fullname')),
                ('bookproductid', models.ForeignKey(db_column='BookProductID', on_delete=django.db.models.deletion.CASCADE, to='ecomapp.Book')),
            ],
            options={
                'db_table': 'author',
            },
        ),
        migrations.AddField(
            model_name='reviewreply',
            name='salesstaffid',
            field=models.ForeignKey(db_column='SalesStaffUsersID', on_delete=django.db.models.deletion.CASCADE, to='ecomapp.Salesstaff'),
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('productid', models.OneToOneField(db_column='ProductID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ecomapp.Product')),
                ('categoryid', models.ForeignKey(db_column='CategoryID', on_delete=django.db.models.deletion.CASCADE, to='ecomapp.Category')),
            ],
            options={
                'db_table': 'product_category',
                'unique_together': {('productid', 'categoryid')},
            },
        ),
        migrations.AddField(
            model_name='messagesession',
            name='salesstaffuserid',
            field=models.ForeignKey(db_column='SalesStaffID', on_delete=django.db.models.deletion.CASCADE, to='ecomapp.Salesstaff'),
        ),
        migrations.CreateModel(
            name='Importingrecord',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, db_column='Date', null=True)),
                ('productid', models.ForeignKey(db_column='ProductID', on_delete=django.db.models.deletion.CASCADE, to='ecomapp.Product')),
                ('supplierid', models.ForeignKey(db_column='SupplierID', on_delete=django.db.models.deletion.CASCADE, to='ecomapp.Supplier')),
                ('warehousestaffid', models.ForeignKey(db_column='WarehouseStaffID', on_delete=django.db.models.deletion.CASCADE, to='ecomapp.Warehousestaff')),
            ],
            options={
                'db_table': 'importingrecord',
            },
        ),
        migrations.CreateModel(
            name='CustomerShippingaddress',
            fields=[
                ('customerid', models.OneToOneField(db_column='CustomerID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ecomapp.Customer')),
                ('shippingaddressid', models.ForeignKey(db_column='ShippingAddressID', on_delete=django.db.models.deletion.CASCADE, to='ecomapp.Shippingaddress')),
            ],
            options={
                'db_table': 'customer_shippingaddress',
                'unique_together': {('customerid', 'shippingaddressid')},
            },
        ),
    ]
