# Generated by Django 3.0.5 on 2021-06-14 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='discountamount',
        ),
        migrations.AddField(
            model_name='voucher',
            name='maxamount',
            field=models.IntegerField(blank=True, db_column='MaxAmount', null=True),
        ),
    ]
