# Generated by Django 3.0.5 on 2021-06-14 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0003_auto_20210614_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='isComplete',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
