# Generated by Django 3.0.5 on 2021-06-14 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0004_payment_iscomplete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerreview',
            name='reviewreplyid',
        ),
        migrations.AddField(
            model_name='customerreview',
            name='isReply',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reviewreply',
            name='customerreviewid',
            field=models.ForeignKey(blank=True, db_column='CustomerreviewID', null=True, on_delete=django.db.models.deletion.CASCADE, to='ecomapp.Customerreview'),
        ),
    ]
