# Generated by Django 3.0.5 on 2021-06-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0005_auto_20210614_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='isUpload',
            field=models.BooleanField(default=False),
        ),
    ]
