# Generated by Django 3.0.5 on 2021-06-14 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0006_item_isupload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewreply',
            name='salesstaffid',
        ),
        migrations.AddField(
            model_name='reviewreply',
            name='staffid',
            field=models.ForeignKey(db_column='SalesStaffUsersID', default=None, on_delete=django.db.models.deletion.CASCADE, to='ecomapp.Staffs'),
            preserve_default=False,
        ),
    ]
