# Generated by Django 3.0.5 on 2021-06-14 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0008_auto_20210614_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importingrecord',
            name='warehousestaffid',
        ),
        migrations.AddField(
            model_name='importingrecord',
            name='staffid',
            field=models.ForeignKey(db_column='StaffID', default=None, on_delete=django.db.models.deletion.CASCADE, to='ecomapp.Staffs'),
            preserve_default=False,
        ),
    ]
