# Generated by Django 3.0.5 on 2021-06-14 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0009_auto_20210614_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='num',
            field=models.IntegerField(db_column='Number', default=0),
        ),
    ]
